### ISSUE TITLE
代码问题

### ISSUE THREAD

**Issue by SongJianHIT** [mansicer/MAIC#12]
您好，请问您 maic_agent.py 代码文件中的 key 和 query 是不是弄反了？你把 trajectory 做成了 key，队友建模采样出来的 latent 作为 query，好像跟您原文不太一样？

**Comment by mansicer** [comment]
谢谢您的反馈！这里的变量名确实存在错误，影响到了阅读。我认为这个错误应该是代码版本原因造成的，但因为时间久远难以回溯。
我检查了以后，此处的错误没有影响到执行正确性，实际的执行过程与paper中的计算一致，是变量的命名出现了问题。这里的key实际上是作为query参与计算的（query也实际起到了key的作用），可以对比参考一些[常见的attention实现](https://github.com/karpathy/nanoGPT/blob/eba36e84649f3c6d840a93092cb779a260544d08/model.py#L67)。
我会在下一个commit里把变量名改正过来，感谢您的指正！

**Comment by SongJianHIT** [comment]
好滴，感谢您的答复~
