### ISSUE TITLE
关于 local policy spaces

### ISSUE THREAD

**Issue by wubmu** [mansicer/MAIC#3]
你好，最近在研读您的文章，有个问题想请教一下。文中提到：
exchange local observation /embedding

This informative communication scheme can reduce uncertainty for individual local decision-
making and induce implicit coordination. However, such a communication mechanism enlarges agents’ local policy
spaces and increases learning complexity,.
我想问下这里的 **enlarges agents’ local policy spaces and increases learning complexity**, 的 local policy spaces是指扩大local observation吗？

**Comment by mansicer** [comment]
Hello. The policy space can be seen as its parameter space, and it will significantly increase when the observation space becomes larger. A major motivation of MAIC is to disentangle the individual policy from heavy communication dependencies. As previous communication baselines often require to take the message as input, it will induce unstability of the agent's own policy.

**Comment by wubmu** [comment]
Thanks for your reply，The ideas in your article are very interesting.
