### ISSUE TITLE
A question about the maps

### ISSUE THREAD

**Issue by LXXXXR** [mansicer/MAIC#5]
Thank you for your wonderful work, and I really enjoyed reading it.

Just a quick question, could you please kindly provide a pointer to the superhard maps(MMM3, 3c_vs_100zg, etc.) that you used for the paper? 

Thanks a lot

**Comment by LXXXXR** [comment]
Thank you for your wonderful work, and I really enjoyed reading it. 

Just a quick question, could you please kindly provide a pointer to the superhard maps(MMM3, 3c_vs_100zg, etc.) that you used for the paper?

**Comment by mansicer** [comment]
Thanks for your interest. All the maps we evaluate can be found [here](https://github.com/mansicer/MAIC/tree/main/qplex_smac/smac/env/starcraft2/maps/SMAC_Maps). A small issue is that we rename the map MMM3 to MMM30 so you may need to modify the map name in your running script. If you have installed StarCraft II with `pymarl`'s default script, you may need to copy these maps to your StarCraft map directory. Please ensure that `SC2PATH` has been set correctly:

```bash
cd <MAIC project directory>
cp qplex_smac/smac/env/starcraft2/maps/SMAC_Maps/* $SC2PATH/Maps/SMAC_Maps/
```

**Comment by LXXXXR** [comment]
Thank you for your prompt reply. That helps a lot.
