### ISSUE TITLE
About the loss function of maximize Mutual Information between a_{j} and latent variable z_{ij}

### ISSUE THREAD

**Issue by minglou1984** [mansicer/MAIC#7]
Why maximize Mutual Information between a_{j} and latent variable z_{ij}？

**Comment by mansicer** [comment]
Hi! Thanks for your interest to our paper. As stated in our paper, this objective of mutual information is used to learn effective teammate representations $\boldsymbol{z}_{ij}$. We propose that maximizing the between the teammate action and the agent representation can serve our purpose properly. I hope you can find more information from our paper.

**Comment by mansicer** [comment]
I will close this issue since no more discussion is involved.
