### ISSUE TITLE
About SMAC maps

### ISSUE THREAD

**Issue by alion2** [mansicer/MAIC#9]
Hello, it's said in the paper that the experiment on SMAC was tested on "all 13 maps",(Figure 6). 
However, $ python -m smac.bin.map_list, would return 38 maps.
Could you please let me know, which 13 maps did you used for the experiments in the paper.

**Comment by mansicer** [comment]
Sorry for the inconvenience. The 13 maps we used include: 

- 2s3z
- 3s5z
- 1c3s5z
- 5m_vs_6m
- 3s_vs_5z
- 2c_vs_64zg
- 10m_vs_12m
- 27m_vs_30m
- 3c_vs_100zg
- 5z_vs_1ul
- 1c3s5z_vs_1c3s6z
- MMM2
- MMM3

We put relevant information in our appendix. It seems that the camera-ready version of AAAI does not include the appendix. We are considering adding a additional link to it. Thanks for your interest to our paper!

**Comment by mansicer** [comment]
I will close this issue since no more discussion is involved.
